export const OBTENER_TIENDAS ='OBTENER_TIENDAS'

//STATE PARA SELECCIONAR TIENDA
 
export const SELECCIONAR_TIENDA ='SELECCIONAR_TIENDA'

export const OBTENER_PRODUCTOS ='OBTENER_PRODUCTOS'

export const OBTENER_PRODUCTOSOFERTA ='OBTENER_PRODUCTOSOFERTA'

//PEDIDO REDUCER

export const SELECCIONAR_PRODUCTO ='SELECCIONAR_PRODUCTO'

export const LLENAR_PRODUCTO ='LLENAR_PRODUCTO'

export const AGREGAR_PRODUCTO ='AGREGAR_PRODUCTO'

export const AGREGAR_PEDIDO ='AGREGAR_PEDIDO'

export const MOSTRAR_TOTAL ='MOSTRAR_TOTAL'

export const ELIMINAR_PRODUCTO ='ELIMINAR_PRODUCTO'

export const GUARDAR_ORDEN ='GUARDAR_ORDEN'

export const ELIMINAR_PEDIDO ='ELIMINAR_PEDIDO'

export const OBTENER_CATEGORIAS_TIENDAS ='OBTENER_CATEGORIAS_TIENDAS'








